"""Portable context bundles — the user-facing memory convention.

A bundle is plain markdown with a fixed section schema. `/ctx:load` reads it,
but so does a person, a wiki, or a different model entirely: pasting the file
into another chat is a supported path, not a fallback. That portability is why
the format carries no dependency on this plugin beyond an optional frontmatter
block.

Project bundles live in the repo so they land in pull requests. Promotion to
the global store is deliberately manual — automatic cross-project recall is how
you get a confident assertion sourced from an unrelated codebase.
"""

import datetime
import re
from pathlib import Path

from . import config as config_mod, frontmatter, paths, redact

SUFFIX = ".ctx.md"

SECTIONS = (
    ("Situation", "Two to five sentences, present tense: what we are doing and why."),
    ("Established facts", "Verified findings a fresh session would otherwise re-derive."),
    ("Decisions made", "Settled choices, with a pointer to the ADR where one exists."),
    ("Open questions", "Unresolved items, as `- [ ]` checkboxes."),
    ("Constraints", "Boundaries that must hold: compatibility, deadlines, scope."),
    ("Artifacts", "Paths, plan files, diff ranges, ticket links."),
    ("Resume here", "The single next concrete action."),
)

_SLUG = re.compile(r"[^a-z0-9]+")


def slugify(name):
    slug = _SLUG.sub("-", str(name).strip().lower()).strip("-")
    return slug or "context"


def template(name, project=None):
    """Skeleton for a model to fill in. Prompts are inline so the shape is obvious."""
    meta = {
        "ctx_bundle": config_mod.SCHEMA,
        "name": slugify(name),
        "scope": "project",
        "created": datetime.date.today().isoformat(),
        "project": project or "",
        "tags": [],
    }
    body = [f"# Context — {slugify(name)}", ""]
    for heading, hint in SECTIONS:
        body += [f"## {heading}", f"<!-- {hint} -->", ""]
    return frontmatter.Document(meta, "\n".join(body))


def save(layout, name, body, tags=None, project=None, config=None):
    """Write a bundle, scrubbing secrets before anything reaches disk."""
    slug = slugify(name)
    patterns = (config or {}).get("redact") or []
    doc = frontmatter.parse(body) if body.lstrip().startswith("---") else None
    if doc is None:
        doc = frontmatter.Document(
            {
                "ctx_bundle": config_mod.SCHEMA,
                "name": slug,
                "scope": "project",
                "created": datetime.date.today().isoformat(),
                "project": project or "",
                "tags": list(tags or []),
            },
            body,
        )
    doc.meta.setdefault("ctx_bundle", config_mod.SCHEMA)
    doc.meta["name"] = slug
    doc.meta.setdefault("scope", "project")
    doc.meta.setdefault("created", datetime.date.today().isoformat())
    if tags:
        doc.meta["tags"] = list(tags)
    doc.body = redact.scrub(doc.body, patterns)

    path = layout.contexts / (slug + SUFFIX)
    doc.write(path)
    reindex(layout)
    return path


def resolve(layout, name):
    """Project store, then global store, then treat the argument as a path."""
    slug = slugify(name)
    candidates = [
        layout.contexts / (slug + SUFFIX),
        layout.contexts / name,
        paths.global_layout().contexts / (slug + SUFFIX),
    ]
    candidates.append(Path(name).expanduser())
    for candidate in candidates:
        try:
            if candidate.is_file():
                return candidate
        except OSError:
            continue
    return None


def listing(layout, include_global=True):
    """(scope, name, path, summary) rows for `ctx list` and the index file."""
    rows = []
    for scope, target in (("project", layout), ("global", paths.global_layout())):
        if scope == "global" and not include_global:
            continue
        directory = target.contexts
        if not directory.is_dir():
            continue
        for path in sorted(directory.glob("*" + SUFFIX)):
            doc = frontmatter.read(path)
            summary = ""
            if doc is not None:
                summary = _one_line(doc.section("situation"))
            rows.append((scope, path.name[: -len(SUFFIX)], path, summary))
    return rows


def reindex(layout):
    rows = [row for row in listing(layout, include_global=False)]
    lines = ["# Saved contexts", "", "<!-- regenerated by ctx; one line per bundle -->", ""]
    if rows:
        for _scope, name, path, summary in rows:
            suffix = f" — {summary}" if summary else ""
            lines.append(f"- [{name}]({path.name}){suffix}")
    else:
        lines.append("_none yet — /ctx:save «name» to create one_")
    layout.contexts.mkdir(parents=True, exist_ok=True)
    layout.context_index.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return layout.context_index


def promote(layout, name):
    source = resolve(layout, name)
    if source is None:
        return None
    target_layout = paths.global_layout()
    target_layout.contexts.mkdir(parents=True, exist_ok=True)
    doc = frontmatter.parse(source.read_text(encoding="utf-8"))
    doc.meta["scope"] = "global"
    doc.meta.setdefault("promoted_from", layout.root.parent.name)
    target = target_layout.contexts / (slugify(name) + SUFFIX)
    doc.write(target)
    reindex(target_layout)
    return target


def _one_line(text, limit=110):
    cleaned = " ".join((text or "").split())
    cleaned = re.sub(r"<!--.*?-->", "", cleaned).strip()
    if len(cleaned) > limit:
        cleaned = cleaned[: limit - 1].rstrip() + "…"
    return cleaned
