"""The append-only journal, and the mechanical digest read back from it.

Two properties matter more than anything else here:

* Writes inject nothing into the model's context. They cost disk, not tokens.
* The digest is a *tail*, not a summary. Reading it costs the same on a
  three-year-old repo as on a fresh one, and it never makes a model call.
  Semantic compression is `ctx digest --semantic`, which is explicit and rare.

Entries are pipe-delimited so they diff cleanly in a pull request and parse
with a `split`, and the files are date-partitioned so two agents working the
same day on different branches merge without conflict.
"""

import datetime
import os

from . import redact

SEP = " | "
DIGEST_HEADER = "# Ledger digest"
_DIGEST_NOTE = "<!-- mechanical tail of journal/, regenerated by ctx; safe to delete -->"


def today():
    return datetime.date.today().isoformat()


def append(layout, config, kind, target, note="", when=None):
    """Record one event. Never raises — journalling must not break a session."""
    if not (config.get("journal") or {}).get("enabled", True):
        return None
    try:
        stamp = (when or datetime.datetime.now()).strftime("%H:%M")
        limit = int((config.get("journal") or {}).get("max_line_chars", 200))
        patterns = config.get("redact") or []
        parts = [stamp, str(kind), redact.scrub(str(target), patterns)]
        if note:
            parts.append(redact.scrub(str(note), patterns))
        line = SEP.join(p.replace("|", "/").replace("\n", " ") for p in parts)
        if len(line) > limit:
            line = line[: limit - 1] + "…"

        path = layout.journal_file(today())
        path.parent.mkdir(parents=True, exist_ok=True)
        new = not path.exists()
        with path.open("a", encoding="utf-8") as handle:
            if new:
                handle.write(f"# {today()}\n\n")
            handle.write(line + "\n")
        return line
    except OSError:
        return None


def tail(layout, count):
    """Last `count` entries across day files, newest last, plus an earlier count."""
    files = sorted(p for p in layout.journal.glob("*.md") if p.name != "DIGEST.md")
    collected, earlier = [], 0
    for path in reversed(files):
        lines = [
            f"{path.stem} {line}"
            for line in _entry_lines(path)
        ]
        if len(collected) >= count:
            earlier += len(lines)
            continue
        need = count - len(collected)
        if len(lines) > need:
            earlier += len(lines) - need
            collected = lines[-need:] + collected
        else:
            collected = lines + collected
    return collected, earlier


def _entry_lines(path):
    try:
        text = _read_tail_bytes(path, 64 * 1024)
    except OSError:
        return []
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("<!--"):
            out.append(stripped)
    return out


def _read_tail_bytes(path, limit):
    size = path.stat().st_size
    with path.open("rb") as handle:
        if size > limit:
            handle.seek(size - limit, os.SEEK_SET)
            handle.readline()  # discard the partial first line
        return handle.read().decode("utf-8", errors="replace")


def recent_paths(layout, count=6):
    """Distinct file paths touched most recently — the cheapest useful signal."""
    entries, _ = tail(layout, 40)
    seen = []
    for entry in reversed(entries):
        fields = entry.split(SEP)
        if len(fields) < 3:
            continue
        kind, target = fields[1].strip(), fields[2].strip()
        if kind in ("edit", "write") and target not in seen:
            seen.append(target)
        if len(seen) >= count:
            break
    return seen


def write_digest(layout, config):
    """Regenerate DIGEST.md. Deterministic given the journal contents."""
    lines = int((config.get("journal") or {}).get("digest_lines", 12))
    entries, earlier = tail(layout, lines)
    body = [DIGEST_HEADER, "", _DIGEST_NOTE, ""]
    if entries:
        body += [f"- {entry}" for entry in entries]
        body.append("")
        body.append(
            f"_{len(entries)} shown"
            + (f" · {earlier} earlier entries in journal/_" if earlier else "_")
        )
    else:
        body.append("_no entries yet_")
    layout.journal.mkdir(parents=True, exist_ok=True)
    layout.digest.write_text("\n".join(body) + "\n", encoding="utf-8")
    return layout.digest
