"""The append-only journal, and the mechanical digest read back from it.

Two properties matter more than anything else here:

* Writes inject nothing into the model's context. They cost disk, not tokens.
* The digest is a *tail*, not a summary. Reading it costs the same on a
  three-year-old repo as on a fresh one, and it never makes a model call.
  Semantic compression is `ctx digest --semantic`, which is explicit and rare.

Entries are pipe-delimited so they diff cleanly in a pull request and parse
with a `split`. Files are partitioned twice over: by date, and by *author*.
Date alone was not enough — two people working one repo on one day both
appended to `journal/2026-09-10.md` and both regenerated `DIGEST.md`, so they
conflicted on nearly every merge. An author writes only to their own file, and
every reader merges the files back into one time-ordered stream.

Day files in the pre-author shape (`journal/YYYY-MM-DD.md`) are still read, as
one unattributed stream alongside the per-author files. They are never
rewritten into the new shape: they record no author at all, so "migrating"
them would stamp every historical entry with whoever happened to run the
migration. An unattributed entry is honest; a wrongly attributed one is not.
"""

import datetime
import hashlib
import os
import subprocess

from . import atomic, redact

SEP = " | "
# How much of a day file the read path looks at. The digest is a tail, so the
# bound is what keeps SessionStart flat: 44 ms at 100k entries, and the same on
# a three-year-old repo as on a fresh one. It is a *read* bound only — a caller
# that destroys what it does not read must pass `limit=None`.
TAIL_BYTES = 64 * 1024
DIGEST_HEADER = "# Ledger digest"
_DIGEST_NOTE = "<!-- mechanical tail of journal/, regenerated by ctx; safe to delete -->"

# Separates the date from the author key in a day file name. Two characters, so
# it cannot be produced by the slug (which collapses runs of `-`) and a legacy
# name can never be mistaken for an attributed one.
AUTHOR_SEP = "--"
# An explicit override, for a machine account or a test that needs a known
# author without a git identity to derive one from.
AUTHOR_ENV = "CTX_JOURNAL_AUTHOR"
AUTHOR_MAX = 32
_SLUG_OK = "abcdefghijklmnopqrstuvwxyz0123456789"

# Resolving an author runs `git`, and `append` is called from an edit hook on
# every tool use. Cache per ledger root: the identity does not change inside a
# process's lifetime in any way worth two subprocesses per journalled event.
_AUTHOR_CACHE = {}


def today():
    return datetime.date.today().isoformat()


# --------------------------------------------------------------------------- #
# who is writing
# --------------------------------------------------------------------------- #

def author_key(layout):
    """The current author's journal file key. Slugified, filesystem-safe.

    Resolution order:

    1. `$CTX_JOURNAL_AUTHOR`, for a machine account or a CI identity.
    2. `git config user.email`, then `user.name`, read from the project the
       ledger belongs to — and only when that project really is a git work
       tree, because `git config` happily answers out of the user's *global*
       config from anywhere, which would attribute a ledger in a plain
       directory to whoever last configured git on the box.
    3. `""` — the documented fallback, and deliberately not a hostname, a
       username or a PID. With no git identity there is nothing to attribute
       an entry to that the repository does not already know, and inventing
       one would leak more than the commits in the repo do. An empty key means
       the entry goes to the unattributed stream, `journal/YYYY-MM-DD.md`,
       which is exactly the shape every pre-author entry already has. It is
       deterministic: the same unconfigured checkout always lands there, and
       nothing has to be merged back later.

    Never raises. A failure to identify the author must not stop the append.
    """
    try:
        override = _slug(os.environ.get(AUTHOR_ENV) or "")
        if override:
            return override
        root = layout.root.parent
        key = str(root)
        if key not in _AUTHOR_CACHE:
            _AUTHOR_CACHE[key] = _slug(_git_identity(root))
        return _AUTHOR_CACHE[key]
    except Exception:  # pragma: no cover - identity must never break a write
        return ""


def _slug(value):
    """ASCII, lowercase, `-`-separated, bounded. Empty when nothing survives.

    Truncation gets a hash tail rather than a bare cut, so two long addresses
    sharing a 32-character prefix do not silently share a journal file.
    """
    value = (value or "").strip()
    if not value:
        return ""
    out = []
    for char in value.lower():
        out.append(char if char in _SLUG_OK else "-")
    slug = "-".join(part for part in "".join(out).split("-") if part)
    if not slug:
        return ""
    if len(slug) > AUTHOR_MAX:
        digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]
        slug = slug[: AUTHOR_MAX - 9].rstrip("-") + "-" + digest
    return slug


def _looks_like_git_work_tree(root):
    """Cheap stat-only pre-filter, so the common case spawns no subprocess.

    An empty `.git` directory is not a repository, and asking `git` about one
    costs a process launch to be told so. `.git` as a *file* is a worktree or a
    submodule, which is a real work tree.
    """
    try:
        for candidate in [root, *root.parents]:
            marker = candidate / ".git"
            if marker.is_file():
                return True
            if marker.is_dir() and (marker / "HEAD").exists():
                return True
    except OSError:
        return False
    return False


def _git(root, *args):
    try:
        done = subprocess.run(
            ["git", "-C", str(root), *args],
            stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return done.stdout.strip() if done.returncode == 0 else ""


def _git_identity(root):
    """`user.email`, else `user.name`, else `""`. Never raises."""
    if not _looks_like_git_work_tree(root):
        return ""
    if _git(root, "rev-parse", "--is-inside-work-tree") != "true":
        return ""
    for key in ("user.email", "user.name"):
        found = _git(root, "config", "--get", key)
        if found:
            return found
    return ""


def day_file(layout, day, author=None):
    """Where `day`'s entries by `author` live. Legacy shape when unattributed."""
    key = author_key(layout) if author is None else author
    if not key:
        return layout.journal_file(day)
    return layout.journal / f"{day}{AUTHOR_SEP}{key}.md"


# --------------------------------------------------------------------------- #
# writing
# --------------------------------------------------------------------------- #

def append(layout, config, kind, target, note="", when=None):
    """Record one event. Never raises — journalling must not break a session."""
    if not (config.get("journal") or {}).get("enabled", True):
        return None
    try:
        # `when` sets the day file as well as the time in the line. It used to
        # set only the time, so a backdated entry landed in today's file and the
        # parameter quietly meant something other than it said.
        moment = when or datetime.datetime.now()
        stamp = moment.strftime("%H:%M")
        day = moment.date().isoformat()
        limit = int((config.get("journal") or {}).get("max_line_chars", 200))
        patterns = config.get("redact") or []
        parts = [stamp, str(kind), redact.scrub(str(target), patterns)]
        if note:
            parts.append(redact.scrub(str(note), patterns))
        line = SEP.join(p.replace("|", "/").replace("\n", " ") for p in parts)
        if len(line) > limit:
            line = line[: limit - 1] + "…"

        path = day_file(layout, day)
        path.parent.mkdir(parents=True, exist_ok=True)
        new = not path.exists()
        # One `write` of one line, appended: that is what makes a concurrent
        # append line-atomic. The author partition removes the *merge* conflict
        # between two people; it does not replace this guarantee, because one
        # author can still have several agents running at once.
        with path.open("a", encoding="utf-8") as handle:
            if new:
                handle.write(f"# {day}\n\n")
            handle.write(line + "\n")
        return line
    except OSError:
        return None


# --------------------------------------------------------------------------- #
# reading — every author, plus the legacy stream, as one thing
# --------------------------------------------------------------------------- #

def _day_files(layout):
    """`(day, author, path)` for every day file. Oldest first, `""` for legacy."""
    try:
        found = list(layout.journal.glob("*.md"))
    except OSError:
        return []
    rows = []
    for path in found:
        if path.name == "DIGEST.md" or path.name.startswith("archive-"):
            continue
        day, _, author = path.stem.partition(AUTHOR_SEP)
        try:
            datetime.date.fromisoformat(day)
        except ValueError:
            continue
        rows.append((day, author, path))
    rows.sort(key=lambda row: (row[0], row[1], row[2].name))
    return rows


def legacy_day_files(layout):
    """Day files in the pre-author shape, oldest first. Read, never rewritten."""
    return [path for _day, author, path in _day_files(layout) if not author]


def _stamp(line):
    """The `HH:MM` an entry opens with, or `""` for anything hand-written."""
    head = line.split(SEP, 1)[0].strip()
    if len(head) == 5 and head[2] == ":" and head[:2].isdigit() and head[3:].isdigit():
        return head
    return ""


def _day_entries(files, limit=TAIL_BYTES):
    """One day's entries across every author, time-ordered.

    `files` is `[(author, path)]`. Ties on the minute are broken by author and
    then by position in the file, so the merge is stable and two clones of the
    same tree always produce the same order.
    """
    rows = []
    for author, path in sorted(files, key=lambda item: (item[0], item[1].name)):
        for index, line in enumerate(_entry_lines(path, limit)):
            rows.append((_stamp(line), author, index, line))
    rows.sort(key=lambda row: row[:3])
    return [row[3] for row in rows]


def tail(layout, count):
    """Last `count` entries across every author's files, newest last.

    Returns `(entries, earlier)`. Each entry is prefixed with its date, not its
    file name: the file name now carries an author key, and the digest, the
    briefing and `recent_paths` all parse the text positionally.
    """
    by_day = {}
    for day, author, path in _day_files(layout):
        by_day.setdefault(day, []).append((author, path))

    collected, earlier = [], 0
    for day in sorted(by_day, reverse=True):
        lines = [f"{day} {line}" for line in _day_entries(by_day[day])]
        if count <= 0 or len(collected) >= count:
            earlier += len(lines)
            continue
        need = count - len(collected)
        if len(lines) > need:
            earlier += len(lines) - need
            collected = lines[-need:] + collected
        else:
            collected = lines + collected
    return collected, earlier


def _entry_lines(path, limit=TAIL_BYTES):
    """Entry lines from one day file, comments and blanks dropped.

    `limit` caps the read at the last `limit` bytes, which is right for every
    reader — they all want a tail. It is wrong for `prune`, which unlinks the
    day file after folding it: whatever the read misses is gone from history,
    and a busy day passes 64 KiB at around 1,130 entries when every edit hook
    appends one. `prune` therefore passes `limit=None` and reads the file whole.
    """
    try:
        if limit is None:
            text = path.read_text(encoding="utf-8", errors="replace")
        else:
            text = _read_tail_bytes(path, limit)
    except OSError:
        return []
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("<!--"):
            out.append(stripped)
    return out


def _read_tail_bytes(path, limit):
    size = path.stat().st_size
    with path.open("rb") as handle:
        if size > limit:
            handle.seek(size - limit, os.SEEK_SET)
            handle.readline()  # discard the partial first line
        return handle.read().decode("utf-8", errors="replace")


def recent_paths(layout, count=6):
    """Distinct file paths touched most recently — the cheapest useful signal."""
    entries, _ = tail(layout, 40)
    seen = []
    for entry in reversed(entries):
        fields = entry.split(SEP)
        if len(fields) < 3:
            continue
        kind, target = fields[1].strip(), fields[2].strip()
        if kind in ("edit", "write") and target not in seen:
            seen.append(target)
        if len(seen) >= count:
            break
    return seen


# --------------------------------------------------------------------------- #
# retiring
# --------------------------------------------------------------------------- #

def prune(layout, config, before=None, archive=True):
    """Fold day files older than `before` into one archive per month.

    One committed file per active day per author, forever, means hundreds a
    year in every clone and every diff. Rolling them up keeps the history — the
    digest is a tail, so it is unaffected either way — while collapsing the
    file count. Per-author files and the legacy unattributed ones retire the
    same way, merged into one section per day.

    Returns (folded_paths, archive_paths).
    """
    if before is None:
        keep = int((config.get("journal") or {}).get("keep_days", 0) or 0)
        if keep <= 0:
            return [], []
        before = datetime.date.today() - datetime.timedelta(days=keep)

    by_month = {}
    for day_name, author, path in _day_files(layout):
        day = datetime.date.fromisoformat(day_name)
        if day >= before:
            continue
        by_month.setdefault(day.strftime("%Y-%m"), {}).setdefault(day, []) \
            .append((author, path))

    folded, archives = [], []
    for month in sorted(by_month):
        days = by_month[month]
        target = layout.journal / f"archive-{month}.md"
        lines = []
        if target.is_file():
            lines.append(target.read_text(encoding="utf-8").rstrip("\n"))
        else:
            lines.append(f"# {month} — archived journal")
        for day in sorted(days):
            # Read each day whole: the files are unlinked below, so a tail read
            # here would not fold the history, it would delete it.
            entries = _day_entries(days[day], limit=None)
            if entries:
                lines.append("")
                lines.append(f"## {day.isoformat()}")
                lines.extend(entries)

        if archive:
            try:
                # Atomic, because this file is the *only* copy of every month
                # an earlier prune already folded into it — the day files it
                # came from were unlinked then. A plain `write_text` truncates
                # first, so a crash mid-write destroys history with no source
                # left to rebuild it from.
                atomic.write_text(target, "\n".join(lines) + "\n")
            except OSError:
                # The archive did not land. Leave this month's day files alone:
                # an unwritten archive plus deleted inputs is the total-loss
                # case, and keeping them means the next run simply retries.
                continue
            archives.append(target)

        for day in sorted(days):
            for _author, path in days[day]:
                try:
                    path.unlink()
                except OSError:
                    pass
                folded.append(path)
    return folded, archives


def write_digest(layout, config):
    """Regenerate DIGEST.md. Deterministic given the journal contents."""
    lines = int((config.get("journal") or {}).get("digest_lines", 12))
    entries, earlier = tail(layout, lines)
    body = [DIGEST_HEADER, "", _DIGEST_NOTE, ""]
    if entries:
        body += [f"- {entry}" for entry in entries]
        body.append("")
        body.append(
            f"_{len(entries)} shown"
            + (f" · {earlier} earlier entries in journal/_" if earlier else "_")
        )
    else:
        body.append("_no entries yet_")
    # Atomic for the same reason as the archive, with one more: the digest is
    # read by SessionStart on every session, so a torn one is read immediately.
    atomic.write_text(layout.digest, "\n".join(body) + "\n")
    return layout.digest
