"""Plans, units and waves.

A plan is a directory of unit files plus a generated graph. The unit files are
the authored artifact; `plan.json` is derived from them, so `depends_on` is the
single source of truth for ordering and nobody has to keep a wave number in sync
by hand.

Two safety checks run before anything is dispatched, and both are decidable by
this module without a model:

* **Disjoint ownership.** Two units in the same wave may not declare overlapping
  `owns`. That is what makes parallel writes safe rather than hopeful.
* **No read/write races.** A unit that *reads* a path another unit in the same
  wave *owns* would read a file mid-rewrite. `owns` sets can be disjoint and this
  can still be wrong, which is why it is a separate check.

Neither is auto-repaired. Both report the exact `depends_on` line that fixes
them — rewriting someone's dependency graph silently is not a favour.
"""

import datetime
import fnmatch
import json
import os
import re

from . import config as config_mod, frontmatter, verify

TIERS = ("inline", "subagent", "session")
STATUSES = ("pending", "running", "blocked", "verify_failed", "done")

REQUIRED = ("unit", "tier", "owns")
_UNIT_NAME = re.compile(r"^[0-9]{2}-[a-z0-9][a-z0-9-]*$")

UNIT_TEMPLATE = """## Objective
{objective}

## Interfaces
<!-- What this consumes from earlier units, and what it produces that later units
     depend on. Name exact signatures: a sibling unit is relying on them. -->

## Acceptance criteria
1. <checkable — name the observable, not the implementation>
2. No file outside `owns` is modified.

## Return contract
Report: files changed · which criteria passed · verbatim verify output · any
interface you were forced to change (that blocks the wave).
"""


class Unit:
    def __init__(self, path, doc):
        self.path = path
        self.doc = doc
        self.name = str(doc.meta.get("unit") or path.stem)

    def __repr__(self):
        return f"<Unit {self.name} wave={self.wave} tier={self.tier}>"

    def _list(self, key):
        value = self.doc.meta.get(key) or []
        if isinstance(value, str):
            value = [value]
        return [str(item) for item in value if str(item).strip()]

    depends_on = property(lambda self: self._list("depends_on"))
    owns = property(lambda self: self._list("owns"))
    reads = property(lambda self: self._read_paths())
    forbid = property(lambda self: self._list("forbid"))

    @property
    def tier(self):
        tier = str(self.doc.meta.get("tier") or "").strip().lower()
        return tier if tier in TIERS else ""

    @property
    def status(self):
        status = str(self.doc.meta.get("status") or "pending").strip().lower()
        return status if status in STATUSES else "pending"

    @property
    def wave(self):
        try:
            return int(self.doc.meta.get("wave"))
        except (TypeError, ValueError):
            return None

    @property
    def budget(self):
        try:
            return int(self.doc.meta.get("budget_tokens") or 0)
        except (TypeError, ValueError):
            return 0

    @property
    def checks(self):
        return self.doc.meta.get("verify") or []

    def _read_paths(self):
        """`reads` may be bare paths or {path, symbols} mappings."""
        out = []
        raw = self.doc.meta.get("reads") or []
        if isinstance(raw, str):
            raw = [raw]
        for entry in raw:
            if isinstance(entry, dict):
                path = entry.get("path")
                if path:
                    out.append(str(path))
            elif str(entry).strip():
                out.append(str(entry))
        return out

    def set(self, **changes):
        self.doc.meta.update(changes)
        self.doc.write(self.path)


# --------------------------------------------------------------------------- #
# layout
# --------------------------------------------------------------------------- #

def plan_dir(layout, slug):
    return layout.plans / slug


def units_dir(layout, slug):
    return plan_dir(layout, slug) / "units"


def graph_path(layout, slug):
    return plan_dir(layout, slug) / "plan.json"


def readme_path(layout, slug):
    return plan_dir(layout, slug) / "README.md"


def create(layout, slug, spec_slug=None):
    units_dir(layout, slug).mkdir(parents=True, exist_ok=True)
    path = readme_path(layout, slug)
    if not path.exists():
        path.write_text(
            f"# Plan — {slug}\n\n"
            f"Spec: `.ctx/specs/{spec_slug or slug}/spec.md`\n\n"
            "## Approach\n"
            "<!-- One paragraph: how the work was cut up, and why along these lines. -->\n\n"
            "## Units\n"
            "<!-- Regenerated by `ctx plan-check`. -->\n\n"
            "## Out of scope\n",
            encoding="utf-8",
        )
    return path


def scaffold_unit(layout, slug, name, objective="", tier="subagent", owns=(), verify_checks=()):
    """Write an empty unit file for the model to fill in."""
    path = units_dir(layout, slug) / f"{name}.md"
    if path.exists():
        return path, False
    meta = {
        "ctx_schema": config_mod.SCHEMA,
        "unit": name,
        "plan": slug,
        "tier": tier,
        "depends_on": [],
        "owns": list(owns),
        "reads": [],
        "forbid": [],
        "budget_tokens": 45000,
        "status": "pending",
        "verify": list(verify_checks),
    }
    body = UNIT_TEMPLATE.format(objective=objective or "<one sentence: the observable outcome>")
    frontmatter.Document(meta, body).write(path)
    return path, True


def load_units(layout, slug):
    directory = units_dir(layout, slug)
    if not directory.is_dir():
        return []
    out = []
    for path in sorted(directory.glob("*.md")):
        doc = frontmatter.read(path)
        if doc is not None:
            out.append(Unit(path, doc))
    return out


# --------------------------------------------------------------------------- #
# validation
# --------------------------------------------------------------------------- #

def validate(units):
    """Structural problems, independent of scheduling. Empty list means valid."""
    problems = []
    if not units:
        return ["no unit files — write .ctx/plans/<slug>/units/NN-name.md first"]

    names = [u.name for u in units]
    duplicates = {n for n in names if names.count(n) > 1}
    for name in sorted(duplicates):
        problems.append(f"duplicate unit name {name!r}")

    known = set(names)
    for unit in units:
        if not _UNIT_NAME.match(unit.name):
            problems.append(
                f"{unit.name}: name must be NN-kebab-case (the prefix orders the plan)"
            )
        for field in REQUIRED:
            if field == "owns":
                if not unit.owns and unit.tier != "inline":
                    problems.append(
                        f"{unit.name}: `owns` is empty — a unit with no declared write "
                        "scope cannot be checked for collisions"
                    )
            elif not unit.doc.meta.get(field):
                problems.append(f"{unit.name}: missing `{field}`")
        if unit.doc.meta.get("tier") and not unit.tier:
            problems.append(
                f"{unit.name}: tier {unit.doc.meta.get('tier')!r} is not one of "
                + "/".join(TIERS)
            )
        if not verify.ordered(unit.checks):
            problems.append(
                f"{unit.name}: no usable `verify` checks — the done-gate cannot hold"
            )
        for dependency in unit.depends_on:
            if dependency not in known:
                problems.append(f"{unit.name}: depends_on unknown unit {dependency!r}")
            if dependency == unit.name:
                problems.append(f"{unit.name}: depends on itself")
    return problems


def waves(units):
    """(wave_number -> [Unit], problems). Wave 1 has no unmet dependencies."""
    by_name = {u.name: u for u in units}
    depth, problems = {}, []
    remaining = set(by_name)

    while remaining:
        ready = [
            name for name in remaining
            if all(
                dependency not in remaining
                for dependency in by_name[name].depends_on
                if dependency in by_name
            )
        ]
        if not ready:
            cycle = ", ".join(sorted(remaining))
            problems.append(f"dependency cycle among: {cycle}")
            break
        for name in sorted(ready):
            dependencies = [
                depth[d] for d in by_name[name].depends_on if d in depth
            ]
            depth[name] = (max(dependencies) + 1) if dependencies else 1
            remaining.discard(name)

    grouped = {}
    for name, level in depth.items():
        grouped.setdefault(level, []).append(by_name[name])
    for level in grouped:
        grouped[level].sort(key=lambda u: u.name)
    return grouped, problems


def collisions(wave_units):
    """Ownership overlaps and read/write races within a single wave."""
    problems = []
    for index, first in enumerate(wave_units):
        for second in wave_units[index + 1:]:
            shared = _overlap(first.owns, second.owns)
            if shared:
                problems.append(
                    f"{first.name} and {second.name} both own {', '.join(sorted(shared))} "
                    f"— add `depends_on: [{first.name}]` to {second.name} or split the paths"
                )
    for reader in wave_units:
        for writer in wave_units:
            if reader.name == writer.name:
                continue
            racing = _overlap(reader.reads, writer.owns)
            if racing:
                problems.append(
                    f"{reader.name} reads {', '.join(sorted(racing))} while {writer.name} "
                    f"rewrites it — add `depends_on: [{writer.name}]` to {reader.name}"
                )
    return problems


def _overlap(left, right):
    """Paths in `left` covered by a pattern or prefix in `right`, and vice versa."""
    found = set()
    for a in left:
        for b in right:
            if _covers(a, b) or _covers(b, a):
                found.add(a)
    return found


def _covers(path, pattern):
    path = str(path).replace(os.sep, "/").rstrip("/")
    pattern = str(pattern).replace(os.sep, "/").rstrip("/")
    if not path or not pattern:
        return False
    if path == pattern:
        return True
    if fnmatch.fnmatch(path, pattern):
        return True
    return path.startswith(pattern + "/")


def check(layout, slug):
    """Full pre-dispatch check. (grouped_waves, problems)."""
    units = load_units(layout, slug)
    problems = validate(units)
    if problems:
        return {}, problems
    grouped, problems = waves(units)
    for level in sorted(grouped):
        problems.extend(
            f"wave {level}: {problem}" for problem in collisions(grouped[level])
        )
    return grouped, problems


def apply_waves(grouped):
    """Write the computed wave back into each unit so it is visible on disk."""
    for level, units in grouped.items():
        for unit in units:
            if unit.wave != level:
                unit.set(wave=level)


def write_graph(layout, slug, grouped, spec_slug=None):
    """Derive plan.json. Prior revisions are archived, never overwritten."""
    path = graph_path(layout, slug)
    revision = 1
    if path.is_file():
        try:
            previous = json.loads(path.read_text(encoding="utf-8"))
            revision = int(previous.get("revision", 1)) + 1
            archive = plan_dir(layout, slug) / "revisions"
            archive.mkdir(parents=True, exist_ok=True)
            (archive / f"plan.r{previous.get('revision', 1)}.json").write_text(
                json.dumps(previous, indent=2) + "\n", encoding="utf-8"
            )
        except (OSError, ValueError):
            revision = 1

    graph = {
        "ctx_schema": config_mod.SCHEMA,
        "plan": slug,
        "spec": spec_slug or slug,
        "revision": revision,
        "generated": datetime.date.today().isoformat(),
        "waves": [
            [unit.name for unit in grouped[level]] for level in sorted(grouped)
        ],
        "units": {
            unit.name: {
                "tier": unit.tier,
                "wave": level,
                "depends_on": unit.depends_on,
                "owns": unit.owns,
                "reads": unit.reads,
                "forbid": unit.forbid,
                "budget_tokens": unit.budget,
            }
            for level in sorted(grouped)
            for unit in grouped[level]
        },
    }
    path.write_text(json.dumps(graph, indent=2) + "\n", encoding="utf-8")
    return path, revision


def render_readme_units(layout, slug, grouped):
    """Keep the human-facing Units section in step with the graph."""
    path = readme_path(layout, slug)
    if not path.is_file():
        return None
    lines = []
    for level in sorted(grouped):
        lines.append(f"**Wave {level}** — these may run concurrently")
        lines.append("")
        for unit in grouped[level]:
            objective = " ".join(unit.doc.section("objective").split())[:110]
            lines.append(
                f"- `{unit.name}` ({unit.tier}, {unit.status}) — {objective}"
            )
            if unit.owns:
                lines.append(f"  - owns: {', '.join(unit.owns)}")
        lines.append("")
    body = "\n".join(lines).rstrip() + "\n"

    text = path.read_text(encoding="utf-8")
    pattern = re.compile(r"(^## Units\s*$)(.*?)(?=^## |\Z)", re.M | re.S)
    if pattern.search(text):
        text = pattern.sub(lambda m: f"{m.group(1)}\n\n{body}\n", text, count=1)
    else:
        text = text.rstrip() + f"\n\n## Units\n\n{body}"
    path.write_text(text, encoding="utf-8")
    return path


def board(layout, slug):
    """Rows for the status board: (wave, unit, tier, status, owns)."""
    grouped, problems = check(layout, slug)
    rows = []
    for level in sorted(grouped):
        for unit in grouped[level]:
            rows.append((level, unit.name, unit.tier, unit.status, unit.owns))
    return rows, problems


def next_wave(layout, slug):
    """Lowest wave with unfinished units, or None when the plan is complete."""
    grouped, problems = check(layout, slug)
    if problems:
        return None
    for level in sorted(grouped):
        if any(unit.status != "done" for unit in grouped[level]):
            return level
    return None


def find_unit(layout, slug, name):
    for unit in load_units(layout, slug):
        if unit.name == name:
            return unit
    return None
